#!/usr/bin/env python
from misc.utility.scons_hints import *

import editor_builders

Import("env")

env.CommandNoCache(
    "#editor/ai_component/agent/best_practices.gen.h",
    "#editor/ai_component/agent/best_practices.md",
    env.Run(editor_builders.make_ai_best_practices_header),
)

env.add_source_files(env.editor_sources, "*.cpp")
