short_name = "next"
name = "NEXT Engine"
next_major = 0
next_minor = 0
next_status = "preview"
major = 4
minor = 7
patch = 1
status = "rc"
module_config = ""
website = "https://godotengine.org"
docs = "4.7"
